// Domain Models matching the requested Schema

export enum UserRole {
  PARENT_A = 'PARENT_A',
  PARENT_B = 'PARENT_B',
  CHILD = 'CHILD'
}

export interface User {
  id: string;
  full_name: string;
  email: string;
  phone_number?: string;
  avatar_url?: string;
  is_premium: boolean;
  report_credits: number; // Pay-Per-Report model
  family_id?: string; // Nullable if not joined yet
}

export interface Family {
  id: string;
  name: string;
  invite_code: string;
  invited_parent_phone?: string; // For Soft Onboarding
  children: ChildProfile[];
}

export interface ChildProfile {
  id: string;
  name: string;
  age: number;
}

export enum EventType {
  CUSTODY = 'CUSTODY',
  EVENT = 'EVENT',
  APPOINTMENT = 'APPOINTMENT',
  NATIVE = 'NATIVE' // Google/Apple events
}

export enum EventStatus {
  PROPOSED = 'PROPOSED',
  APPROVED = 'APPROVED',
  DENIED = 'DENIED',
  COMPLETED = 'COMPLETED'
}

export interface CalendarEvent {
  id: string;
  family_id?: string; // Optional for Native events
  created_by?: string;
  title: string;
  start_time: string; // ISO String
  end_time: string; // ISO String
  type: EventType;
  status: EventStatus;
  is_immutable: boolean;
  color?: string; // For UI differentiation
  source?: 'APP' | 'GOOGLE' | 'APPLE';
}

export enum ExpenseCategory {
  MEDICAL = 'רפואי',
  EDUCATION = 'חינוך',
  CLOTHING = 'ביגוד',
  FOOD = 'מזון',
  OTHER = 'אחר'
}

export interface SplitDetail {
  user_id: string;
  percentage: number; // 0-1 (e.g., 0.5 for 50%)
  amount_owed: number;
}

export interface Expense {
  id: string;
  family_id: string;
  paid_by: string; // User ID
  amount: number;
  description: string;
  category: ExpenseCategory;
  date_incurred: string;
  receipt_url?: string; // Legacy URL if exists
  receipt_image_path?: string; // New Supabase Storage path
  split_details: SplitDetail[]; // JSONB column equivalent
  is_settled: boolean;
}

export interface Message {
  id: string;
  family_id: string;
  sender_id: string;
  content: string;
  created_at: string;
  is_flagged_by_ai: boolean;
  is_rewritten: boolean; // Was this message generated by AI?
}

export interface LegalAuditLog {
  id: string;
  user_id: string;
  original_text: string;
  ai_rewritten_text: string;
  timestamp: string;
}

export interface SentimentResult {
  isAggressive: boolean;
  reason: string;
  suggestedRewrite: string;
}

export enum PaymentProvider {
  BIT = 'BIT',
  MESHULAM = 'MESHULAM', // Credit Card Gateway common in Israel
  APPLE_PAY = 'APPLE_PAY'
}

export interface PaymentTransaction {
  id: string;
  amount: number;
  currency: 'ILS';
  provider: PaymentProvider;
  status: 'PENDING' | 'COMPLETED' | 'FAILED';
  date: string;
}